### PR TITLE
UML Inital merge. Please look at and amend

### PR DESCRIPTION
**Pull request by afontaine**
Addresses issue #6

### CODE REVIEW

**Comment by jviau** [comment]
1. Top 3 classes need to be fleshed out.
2. StoryDb to Story to WebService is still undecided. We know we eventually need a local Db to cache stories offline. So what we need is StoryManager object that then connects to both the WebService and Local Db. Story should only associate to the StoryManager and not directly to the WebService or Local DB.

**Comment by afontaine** [comment]
DON'T merge this yet, or we'll lose our project.

**Comment by afontaine** [comment]
@jesseDtucker and @jviau, Storys have a collection of ids for all StoryFragments that are a part of the Story. StoryFragments know all their choices. Is this what we agreed on last night?

**Comment by Jtfinlay** [comment]
I approve of the new changes. We need to merge the other pull request first however, because Andrew did some cleaning on his system.

Edit - @afontaine looks like you'll have to fix the issues before we merge.

**Comment by jesseDtucker** [comment]
"@jesseDtucker and @jviau, Storys have a collection of ids for all StoryFragments that are a part of the Story. StoryFragments know all their choices. Is this what we agreed on last night?"

Storyfragments should know their choices, in both what is the next fragment and the text to display.

Questions/comments about UML:
- Webservice doesn't handle create, update or delete. Just publish *ie update with create. (Talked to Jacob about this, we'll refine as we go).
- Shouldn't webservice have a getFragment if we want to do lazy loading?
- We need a get bookmark accessor.
- Why do we need a resume story? shouldn't the view just select a bookmark then select the corrosponding story? The other way works but just seems like unneeded indirection.
- Do stories have a top level logo or image, something to go with synopsis.
- How do we fetch comments for a fragment? Probably need an accessor.

@Jtfinlay and I need to examine the view layout a bit more.

**Pull request closed without merging**
