### PR TITLE
Initial "Hello World" app

### PR DESCRIPTION
**Pull request by afontaine**
And README update

### CODE REVIEW

**Comment by edegraff** [comment]
Looks good.

**Comment by Jtfinlay** [comment]
Quick question before I approve - are we caring whether the license info is at the top or the java files from the get-go, or is that something we'll just toss in later?

Other than the license missing it looks fine.

**Comment by afontaine** [comment]
I can toss it in later before we pull it in, and figure out what to put. This was all auto-generated stuff, so I'm not too concerned about it.

**Comment by Jtfinlay** [comment]
Sounds good, merging.

**Pull request merged**
