### PR TITLE
Image stuff

### PR DESCRIPTION
**Pull request by afontaine**
Changing and saving images on Story and StoryFragments work.

Please try to beat the :poop: out of it, as there might still be some bugs lurking.

You might notice the default story isn't a black square on the server anymore, that was me.

### CODE REVIEW

**Comment by afontaine** [comment]
Also makes #93 redundant

**Comment by jviau** [comment]
StoryDBTest.testSetStory() is failing on a null pointer exception during the setImage() call.

**Comment by afontaine** [comment]
Okay, will look into

**Comment by afontaine** [comment]
All fixed now. @edegraff, get those AuthorController tests sorted out!

**Comment by jviau** [comment]
Umm, you changed the test to fit the commit. That's not how it works. Change the test back and fix whatever it was inside of StoryDB that throws the null pointer exception. And yes, a story can have a null thumbnail if thats the case. That's what the default image in XML is for.

**Comment by afontaine** [comment]
Right, buuuut the thumbnail isn't null when it goes into the DB. In one of the controllers, if the thumbnail is still null, it gets set to grumpy cat. Essentially, according to what we have, there should never be a null thumbnail going into or coming out of the database. It's not about whether or not the Story thumbnail can be null, it's about what's going into the database.

**Comment by jviau** [comment]
What the controller does is irrelevant. The dB should be agnostic as to what the state of the object it is saving is. This way the controller can change its behavior as needed and not have to worry about passing the dB something that will break it.

**Comment by afontaine** [comment]
Being agnostic to the state of the object is a good way to lead to a mucked up DB. If we're strict about what goes in and out, we can maintain DB purity. Now, I can't access the resources from the DB, and I probably shouldn't be trying to grab the resources anyway (that's the controller/view's business considering how strict we're being with the MVC). Best I could do is return false, but at least a NullPointerException forces us to look at the problem.

**Comment by jviau** [comment]
Or how about if its null leave the column as null? And what dB purity are you talking about? How does having a null column on a single object cause any issues? This in no way will lead to a "mucked up" dB.

**Comment by afontaine** [comment]
Or how about we define it as part of the schema that a Story has a thumbnail? Why bother with null-checking when we can simply force it? If you want to change it, you can. I've got more important assignments to work on.

**Comment by Jtfinlay** [comment]
Looks decent. I'll implement the View component for storyfragments right now.

Edit: There's a few issues with the View modifications you made. They don't really affect anything until the placeholders are taken out though. The fixes will be in my next pull request once this one has gone through.

**Comment by Jtfinlay** [comment]
Should comments be working..? They don't appear..

Edit: Just text is appearing, but not picutres
Edit 2: Pictures appearing after about 40 seconds.. Internet is slow I guess
Edit 3: I posted two comments on the 'Super Kewl Story, GUIZ' story. One with pic, one without. Somehow they both have the one pic for the dropdown. I'm trying to implement hiding the button if no pic is given.

**Comment by afontaine** [comment]
Yeah, internet is super slow. :frowning:

Did you navigate away from the view before commenting again? It sounds like it's pulling the pic from last time, because it was never re-initialized. Possibly an easy fix...

**Comment by Jtfinlay** [comment]
I'm not sure. i don't think I left the page. I'm trying to post another one but I think my internet is too slow to actually send the query....

Nvrmind, it went through. This time it didn't attach an image. This was a new one though - there may be a bug from the cache in sending a comment w/o a photo attached after sending one with a photo attached.

Edit: Yup, the bug is there. Just did it with the spam pics on the comments.

**Comment by afontaine** [comment]
@Jtfinlay's issue is now fixed. Merging.

**Pull request merged**
