### PR TITLE
Fix for online bookmarks

### PR DESCRIPTION
**Pull request by edegraff**
Online bookmarks should work properly now.

### CODE REVIEW

**Comment by jviau** [comment]
Tested, not functioning properly. When trying to play online the views load very slowly (may just be server response time). But this is causing the dialog choices to become out of sync. Such as for Jame's story, when I got out of bed and turned on the lights it showed the options for "get out of bed" and "turn on lights" still. But choosing one showed the toast for "pickup toothbrush".

And then there is this following exception that continually happens:

11-28 14:24:17.412: E/StoryManager(30716): StoryManager: 
11-28 14:24:17.412: E/StoryManager(30716): android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4746)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:823)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.View.requestLayout(View.java:15480)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.View.requestLayout(View.java:15480)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.View.requestLayout(View.java:15480)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.View.requestLayout(View.java:15480)
11-28 14:24:17.412: E/StoryManager(30716):  at android.widget.ScrollView.requestLayout(ScrollView.java:1440)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.View.requestLayout(View.java:15480)
11-28 14:24:17.412: E/StoryManager(30716):  at android.view.View.requestLayout(View.java:15480)
11-28 14:24:17.412: E/StoryManager(30716):  at android.widget.TextView.checkForRelayout(TextView.java:6446)
11-28 14:24:17.412: E/StoryManager(30716):  at android.widget.TextView.setText(TextView.java:3696)
11-28 14:24:17.412: E/StoryManager(30716):  at android.widget.TextView.setText(TextView.java:3554)
11-28 14:24:17.412: E/StoryManager(30716):  at android.widget.TextView.setText(TextView.java:3529)
11-28 14:24:17.412: E/StoryManager(30716):  at ca.cmput301f13t03.adventure_datetime.view.FragmentView.setUpView(FragmentView.java:118)
11-28 14:24:17.412: E/StoryManager(30716):  at ca.cmput301f13t03.adventure_datetime.view.FragmentView.OnCurrentFragmentChange(FragmentView.java:78)
11-28 14:24:17.412: E/StoryManager(30716):  at ca.cmput301f13t03.adventure_datetime.model.StoryManager.PublishCurrentFragmentChanged(StoryManager.java:223)
11-28 14:24:17.412: E/StoryManager(30716):  at ca.cmput301f13t03.adventure_datetime.model.StoryManager.access$4(StoryManager.java:221)
11-28 14:24:17.412: E/StoryManager(30716):  at ca.cmput301f13t03.adventure_datetime.model.StoryManager$1.run(StoryManager.java:424)
11-28 14:24:17.412: E/StoryManager(30716):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
11-28 14:24:17.412: E/StoryManager(30716):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
11-28 14:24:17.412: E/StoryManager(30716):  at java.lang.Thread.run(Thread.java:856)

**Comment by edegraff** [comment]
Not really related to the bookmarks, but I'll put the fix here anyway.  This commit fixes the threading exception, which appears to have been causing the out of sync issues too.

**Comment by jviau** [comment]
Ok I wasn't sure what the problem is, I will re-test though

**Comment by jviau** [comment]
Playing online is much smoother, bookmarks work. Didn't notice any exceptions in the log. It is however a bit laggy when swiping from "my stories" to "online" and back. But that can be investigated if we have time. Approved otherwise.

**Comment by Jtfinlay** [comment]
When I have an online bookmark set, the 'Continue' button appears on home screen, but no bookmarks are listed.

**Comment by edegraff** [comment]
ContinueView looks in the list of localStories, so the online story won't be in there.  We can either modify it so it checks the list of onlineStories or we can have onlineStories not affect ContinueView at all.

**Comment by Jtfinlay** [comment]
Not at all works for me. Can you implement? I'm working on removing all
image placeholders.

**Comment by edegraff** [comment]
Will do.

**Comment by edegraff** [comment]
Checking the list of onlineStories turned out to be easier.  Online bookmarks should show up properly now, with a slight delay for server loading.

**Comment by afontaine** [comment]
Totally works now. Good job, @edegraff. I approve.

**Comment by Jtfinlay** [comment]
Server is being shit right now.. fml

**Pull request merged**
