### PR TITLE
Added views & buttons. Would like to merge so that others can expand on the four views.

### PR DESCRIPTION
**Pull request by Jtfinlay**

### CODE REVIEW

**Comment by Jtfinlay** [comment]
If you guys could actually clone and test it on your phones/emulators, that'd be appreciated. The buttons should launch the activities.

Also, something that might need to be implemented with this is how the views communicate with the model. Are we just having the views/activities as observers and the model as observable? Or is there some other way we plan on doing this?

Edit: Talked to Jacob and we could just copy the way DJ Hindle does it, but with some observable modifications. He uses a separate FillerCreepApplication though. Thoughts?

**Comment by jesseDtucker** [comment]
Talked to James already. But we should probably just use an observer pattern with subscription as defined in our UML.

Edit: Also I can't test right now so someone else will have to look this over. Will check again later this afternoon.

**Comment by edegraff** [comment]
Verified to work on my computer.

**Comment by jviau** [comment]
Worked on my phone after dropping the minSdkVersion from 18 (4.3) to 14 (4.0). My phone is 4.2.2.

**Pull request merged**
