### PR TITLE
WebStorage, Comment, Some tests

### LINKED ISSUE #40: Author Publishes Created Story
[Use Case 5](https://github.com/CMPUT301F13T03/adventure.datetime/wiki/5-Author-Publishes-Created-Story) states that Authors should be able to publish Stories to the server. This must be implemented by Nov. 6.

### PR DESCRIPTION
**Pull request by jviau**
Closes #40 and #39

### CODE REVIEW

**Comment by afontaine** [comment]
Looks good to me, @Jtfinlay, think you can hook it up for 3?

**Comment by Jtfinlay** [comment]
Hmmm. no.

**Comment by afontaine** [comment]
Is anyone else going to test this so we can merge it in?

**Comment by edegraff** [comment]
Tested on my setup, and it builds and runs properly.  Approved and merged.

**Pull request merged**
