### PR TITLE
Controllers

### PR DESCRIPTION
**Pull request by edegraff**
Added AuthorController, and implemented more of UserController and StoryManager.

The controllers should now have enough functionality to integrate them with the views for project part 3.

### CODE REVIEW

**Comment by afontaine** [comment]
So... grabbing anything from the DB that isn't actually in there (wrong id) returns null. I'm not sure if that's you or the view who handles that, just commenting so it gets dealt with.

Other than that, looks fine to me :shipit:

**Comment by jesseDtucker** [comment]
Delete story needs to also delete any bookmarks that reference the story.

Edit: also might want to do some null checking as per andrew's comment.

**Comment by jesseDtucker** [comment]
Do we want to do any validation anywhere in here (stretch goal obviously)?

**Comment by jesseDtucker** [comment]
Again, delete fragment will break any bookmarks that refer to that fragment in a story, we can either delete the bookmark or edit it to point somewhere else (head fragment?)

**Comment by edegraff** [comment]
Added the null checking and modified a couple other things.  Will fix the bookmark deletion issue once we have delete functionality in the database.

**Pull request merged**
