### PR TITLE
Added a Use Case template and some use cases

### PR DESCRIPTION
**Pull request by afontaine**

### CODE REVIEW

**Comment by afontaine** [comment]
I guess I also made some fragments of code... IGet and ISet, basic Story model

**Comment by jviau** [comment]
Looks good to me. I will be doing the storage interfaces right away.

**Comment by jesseDtucker** [comment]
3_AuthorAddsStoryFragToStory.md:

"Trigger
+-------
+- Author creates a fragment and selects "Add to ~~Current~~ Story".
+"

I feel like that implies we can add a fragment to a story other than the story it was associated with on create. Just remove the current.

**Comment by Jtfinlay** [comment]
He didn't break the code. Code approved once we're happy with the use cases

**Comment by jesseDtucker** [comment]
3_AuthorCreatesChoice.md:

-multiple use case 3's.
- Flow does not match https://github.com/CMPUT301F13T03/adventure.datetime/wiki/User-Interface-Mockup-&-Storyboard

Change basic flow to:
1. Author is editing story fragment.
2. Author selects add choice

TBC

**Comment by jesseDtucker** [comment]
Talked to Andrew about it.

DONE

**Pull request merged**
