### PR TITLE
Web view pull

### PR DESCRIPTION
**Pull request by jesseDtucker**
This is it! Tons of work went into this, take a look, and test it out. You can create fragments, edit fragments, link fragments, relink fragments, unlink fragments, etc.

Now it is very late and I'm tired. No one bug me before 10 tomorrow because I need sleep, its nearly 3 AM.

Cheers,

-Jesse
# 

Debt:
- ~~updating tree view (aka webview) requires rebuilding entire tree. Not needed but need to implement smarter system, less load for system while editing that way.~~
- refinement of workflows for editing (talked to Evan about this, basically when to select a node, vs create a new one vs transition).
- ~~Horizontal support, as per our early discussions I didn't bother supporting horizontal alignment. The only hiccup here is taking input, rendering appears to work fine.~~
- Multi-touch support: pinch zoom would be a very nice to have, double tap (for re-centering) would be nice as well.
- ~~Animations: I want the path objects to indicate a direction by having a small animation between the fragments in the view.~~
- ~~Integration: Saving seems to have some issues, I think we need to re-examine how we are handling saving. Also I haven't done anything on the preview screen, I was going to refactor the existing fragment view and just reuse but that looks like more work than I would like (@Jtfinlay I want your thoughts on this). Also I haven't tested deletion all the way through yet.~~
- Caching system for node grids, I want to save a grid after it is constructed (just in memory) so I don't have to rebuild it again if we leave and come back later.
- ~~Deleting from the treeview needs to be implemented~~
- ~~Preview screen needs work.~~

### CODE REVIEW

**Comment by Jtfinlay** [comment]
It's still a little buggy. I'll make a small report on the issues I find.

**Comment by Jtfinlay** [comment]
I did the following:
- Made a new story
- Edited the content
- Saved fragment
- Made a new choice (back to itself)
- Went back to BrowseView
- Pressed 'PlayStory'
- Received Error:

" StoryManager -- Rx'd a NULL value from the webstorage for a fragment!"

I'll look at the code and try to find the bug. I also receive a null pointer exception when I go back to edit the story. I believe they are related.

EDIT: Could it be that StoryFragment isn't saving properly? That would explain why it's trying to find it on the server.

**Comment by Jtfinlay** [comment]
I think I fixed it. Could you check [my fix](https://github.com/Jtfinlay/adventure.datetime/tree/jesse_fix), @jesseDtucker ? I'll continue testing and make a cool story.

**Comment by jesseDtucker** [comment]
"Integration: Saving seems to have some issues, I think we need to re-examine how we are handling saving."

That is why I put this in (as well as the log). I was going to talk to you guys about it tomorrow (today I guess). I think that should work for now, but I want to take another look at saving. I'm not sure if we want to single out saving fragments and saving a story or just make it a simple save all. Save all I think would be logically simpler for the end user (else we need to add warning to the UI for unsaved stuff). Think about it, I'll talk to you when I get to school (been awake all of 5 minutes, be there for 379).

**Comment by jesseDtucker** [comment]
Oh, also either keep the phone plugged in and debugging or put it into airplane mode. (essentially kill the internet connection) I was still getting a sigsegv last night. Killing internet appears to have fixed it, but it might not be online as I wasn't testing for it exclusively so it might be some other system.

**Comment by Jtfinlay** [comment]
Haven't had any SIGSEGV's yet. 
For now I'm just testing the pull request and bringing up any issues I see.

Found another minor issue with Choices in AuthorEdit_Edit, where if the text is very long, I cannot see all of the choices that are set.

**Comment by edegraff** [comment]
Saving the entire story like you're talking about might make more sense, it wouldn't take long to modify saveStory or add a new method.

The SIGSEGVs were before you had the server code pulled into your branch Jesse, so they're probably fixed now.  

I'm still getting nodes appearing at large distances from each other occasionally.

After linking fragments together through choices, the line does not appear until I exit editing the story and go back in.

**Comment by jesseDtucker** [comment]
The links not refreshing is a known issue. Its related to this:

"updating tree view (aka webview) requires rebuilding entire tree. Not needed but need to implement smarter system, less load for system while editing that way."

I can't fix that atm (in lab). It'll be a few hours of work to fix but will make the phone chug less on large stories.

**Comment by jesseDtucker** [comment]
Right, so I won't have time to address the issues for a few days. 322 and 379 need to get done. If you want to use whats here pull it in. If not wait and I'll address the issues.

**Comment by Jtfinlay** [comment]
once a fix for saving is merged in, I'll approve it.

**Comment by jesseDtucker** [comment]
Got it, working on improvements right now.

**Comment by jesseDtucker** [comment]
Most issues addressed. Added a new pair that cropped up. I think we oughtta get this in while I work on fixes for the preview screen and deletion while on treeview.

**Comment by edegraff** [comment]
Tested on my device. Saved issues and refreshing issues are fixed, animations look pretty cool.  Direction of the particles is inconsistent though, is there meaning to it?

Approved!

**Comment by jesseDtucker** [comment]
It should be going from the fragment the choice is in to the fragment the choice leads to... I'll double check the direction.

Edit: just tested, they appear to be going in reverse... my bad. good catch. fixing....

**Comment by edegraff** [comment]
They go the right direction now, but I still get the odd one going in the wrong direction.

Another thought, how hard would it be to change the default zoom level?  Having it zoomed out a bit so you can see more of the nodes at once would be nice.

**Comment by jesseDtucker** [comment]
I havent' implemented zoom. I could shrink the resources (bitmaps and text) to a better size

**Comment by edegraff** [comment]
Mhmm, that's what I meant.

**Comment by jesseDtucker** [comment]
K, just finishing up deletion by selection. I'll then be doing preview screen. After that I'll address the size issue. probably just scale everything down a notch.

**Comment by Jtfinlay** [comment]
Looks cool.
The little balls seem to follow a proper path, but I notice the lines tend to shift around as the user pans. Not critical, but noticeable.
I agree with Evan that zoom (or at least being zoomed out more) is important. It's a little too difficult to see everything.

Looking great though! Going to kick ass with this :smiley_cat:

**Comment by jesseDtucker** [comment]
K, I'll have to get the rest tomorrow. Its getting late and I'm out of juice.

@Jtfinlay I will need you help with the preview screen. Also we need to take a look at media in the story edit as I haven't touched it. We can touch base tomorrow.

**Comment by jesseDtucker** [comment]
Preview is fixed

**Comment by jesseDtucker** [comment]
Bah, stupid buttons are hard to hit on phone. Re opened

**Comment by Jtfinlay** [comment]
that looks much better. Approved once you fix merge conflict.
:shipit:

Although -- Still a few issues:
- If text too long, still can't scroll through choices (can only see top one).
- When editing existing choice (such as changing target), the line doesn't update automatically.

**Comment by afontaine** [comment]
Line moving about is fixed.

**Comment by afontaine** [comment]
Works now for sure. Will begin merging. Good job, @jesseDtucker

**Comment by jesseDtucker** [comment]
Ty

**Pull request merged**
