### PR TITLE
Added Bookmark, Choice, and updated StoryFragment

### PR DESCRIPTION
**Pull request by afontaine**
All with just basic setters and 

Not sure why this wasn't in the last pull request... I blame 379

### CODE REVIEW

**Comment by jesseDtucker** [comment]
Mostly approved.

bookmark needs storyId

story fragment needs to have the choices initialized. Also pick a collection type. Arraylist is simple. Get rid of the ugly toArray used to access choices.

**Comment by jesseDtucker** [comment]
Approved.

**Comment by jesseDtucker** [comment]
Would someone else kindly review this as well as the other pull request that have been sitting for a few days?

**Comment by Jtfinlay** [comment]
@afontaine Fix the conflicts and I'll merge

**Comment by afontaine** [comment]
I'll just merge it. :tongue:

**Pull request merged**
