### PR TITLE
Comment

### PR DESCRIPTION
**Pull request by Jtfinlay**
Comments can now be added on all of your favourite Stories and Fragments!

Like, ZOMG!

Edit: We also threw a quick bookmark fix in there as well.

### CODE REVIEW

**Comment by edegraff** [comment]
Tested and approved!

**Comment by Jtfinlay** [comment]
Can one more person test so that we can merge this and the unicorn or?

**Comment by Jtfinlay** [comment]
*pr.

**Comment by jviau** [comment]
Good enough. The new comments not showing up is because ES takes time to index the new comment and then makes it available in requests. So if the controller sets like a 1 second refresh delay to get new comments after creating comment it would work.

Or leave it as is, I don't care.

**Pull request merged**
