### PR TITLE
Database

### PR DESCRIPTION
**Pull request by afontaine**
Here's our initial Database. I want to make some JUnit tests for it, but they look more complicated than I initially thought. Might as well get the actual DB in there. Comment on any missing methods.

I also added some basic JSON parsing. It's untested as of right now, but I'm hoping it works right out.
It uses the [GSON](https://code.google.com/p/google-gson/) library.

### CODE REVIEW

**Comment by jesseDtucker** [comment]
I'm just testing James' pull request, once that is done I'll take a look.

**Comment by jesseDtucker** [comment]
Notes:
- Should the story class have the bitmap or just a string? Ie. should the model just contain a string resource id and the view be responsible for mapping that string to the actual resource?
- Why does getBookmark have an overload for fragment id? There can only be one bookmark per story.
- Why is the insert called set<something>. Shouldn't it be like save<something> or something similar?
- Shouldn't we have a getAllBookmarks? Or did I just miss that?

**Comment by jviau** [comment]
As we discussed, change the constructors to not use Cursors. Either have the dB call a constuctor that has each field as a parameter, or create a blank one then populate it with all the .set() methods.

Cursors are messy and ugly, we don't want them to appear in any class but the dB.

**Comment by afontaine** [comment]
@jesseDtucker 
- This one I'm not sure about... Are the thumbnails going to be saved in local storage? Currently, they're blobbed into
  the DB. If they're saved offline, where are we saving them when not in the DB and how do we access that?
- getBookmark is overloaded mostly because I felt like it... We can take that out.
- It's called set 'cause I just finished a bunch of gets, and I was caught in the get/set stuff of Java
- I missed that one, can add it.

@jviau 
- I just finished changing that over.

**Comment by jesseDtucker** [comment]
@afontaine 
I'm not too particular about the bitmaps. I just considered them to be a view component and so the view is responsible for asking something to resolve its resources. That being said, I'm probably overkilling this. The only reason I say this is that I've had issues with models storing view formats, but that was an issue with portability as different devices support different ways of representing a bitmap. Seeing as we are only doing android it probably doesn't matter at all. 

Also I have no idea how we were planning on storing the images, raw binary dump into database or just free floating files....? Also videos will have the same issue and I don't imagine the DB will appreciate having a video of several megabytes being shoved into it.

**Comment by afontaine** [comment]
Yeah... I'm thinking we just leave the videos to absolutely last. :smile:

**Comment by afontaine** [comment]
After talking with @jviau last night, I'll be transitioning over to a GUID-based table. Probably with the _ID still being auto-incrementing integer for internal android purposes

**Comment by afontaine** [comment]
Database now officially safe to pull in. Tests are located in DatabaseTests on my fork, coming in a pull near you.

**Comment by edegraff** [comment]
Tested and approved

**Comment by Jtfinlay** [comment]
Me gusta. I'll let you know any issues.

:ship: :it:

**Comment by jviau** [comment]
Change the ID's to be of type UUID (and not string). When you go into the database call UUID.toString(), and when you come out of the database call UUID.fromString(string).

**Comment by Jtfinlay** [comment]
Late to the :cake: :(

**Comment by afontaine** [comment]
@jviau Too late. Besides, they won't be of type UUID on the server, .equals() still works fine, and we might as well stay consistent and keep everything as Strings. What's the benefit of having them as UUID instead of String?

**Comment by jviau** [comment]
For code clarity. This way if we try to put a non-UUID into the ID field it will let us know by throwing an exception. Its like storing numbers as strings. Sure you can do it, but it's bad design and just plain wrong.

**Comment by afontaine** [comment]
Well.. alright. I'll add it in in the other open pull request.

**Pull request merged**
