### PR TITLE
Illustrations Bug

### PR DESCRIPTION
**Pull request by afontaine**
Cannot delete illustrations.

If you choose 'Camera,' and then hit 'back', it seems to delete the current illustration.

### CODE REVIEW

**Comment by afontaine** [comment]
Fixed it, @Jtfinlay, please look.

**Comment by jviau** [comment]
Everything seems good. I had an issue with online stories though, where ES went down and for the app to recover I had to kill it and re-open. But otherwise approved.

**Comment by afontaine** [comment]
Fixed. All of it fixed. Somebody test this.

**Comment by jesseDtucker** [comment]
Testing....

**Pull request closed without merging**
