### PR TITLE
Database error with setAuthoredStory()

### PR DESCRIPTION
**Pull request by afontaine**
StoryDB.setAuthoredStory() does not work when calling it on a new story, and throws the following exception when calling it on a downloaded story:

12-02 17:57:12.143: E/AndroidRuntime(30852): FATAL EXCEPTION: main
12-02 17:57:12.143: E/AndroidRuntime(30852): Process: ca.cmput301f13t03.adventure_datetime, PID: 30852
12-02 17:57:12.143: E/AndroidRuntime(30852): java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/ca.cmput301f13t03.adventure_datetime/databases/adventure.database
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1437)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at ca.cmput301f13t03.adventure_datetime.model.StoryDB.setAuthoredStory(StoryDB.java:558)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at ca.cmput301f13t03.adventure_datetime.model.StoryManager.setStoryToAuthor(StoryManager.java:645)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at ca.cmput301f13t03.adventure_datetime.controller.AuthorController.setStoryToAuthor(AuthorController.java:159)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at ca.cmput301f13t03.adventure_datetime.view.StoryDescription.onOptionsItemSelected(StoryDescription.java:204)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.app.Activity.onMenuItemSelected(Activity.java:2599)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1012)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:546)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:115)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.view.View.performClick(View.java:4424)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.view.View$PerformClick.run(View.java:18383)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.os.Handler.handleCallback(Handler.java:733)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.os.Handler.dispatchMessage(Handler.java:95)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.os.Looper.loop(Looper.java:137)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at android.app.ActivityThread.main(ActivityThread.java:4998)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at java.lang.reflect.Method.invokeNative(Native Method)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at java.lang.reflect.Method.invoke(Method.java:515)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
12-02 17:57:12.143: E/AndroidRuntime(30852):    at dalvik.system.NativeStart.main(Native Method)

Any idea why?

### CODE REVIEW

**Comment by afontaine** [comment]
Oh, I clearly accidentally closed something I wasn't supposed to yet. I'll take a look.

**Comment by afontaine** [comment]
It's a really small fix, @edegraff, but give it a shot? It's the only thing I could see possibly getting weird.

**Comment by edegraff** [comment]
Cool, that fixed the exception that was happening, so downloaded stories work now. 

Adding a newly created story still doesn't work for me though, does the story need to exist in the db before its added to authoredStories?

**Comment by afontaine** [comment]
Yeah, I figured there's no pointed adding something to authored stories if it doesn't even exist (sort of) yet. Also, I was running into some null pointers when trying to add it to the AuthoredStories in the StoryManager (involving getting fragments and making them a new UUID). I assume it was because the Story didn't fully download or something... Any ideas?

EDIT: setAuthoredStory() _should_ return false if the Story ID doesn't exist in the DB. Is this the behaviour you are seeing?

**Comment by edegraff** [comment]
Gotcha, makes sense.

Where are you running into the nullPointerException exactly?

**Pull request closed without merging**
