### PR TITLE
IAMA God AMA

### PR DESCRIPTION
**Pull request by Jtfinlay**
It works on my phone. Please tell me it works on yours.

This should fix the issue of bitmap disappearing when moving it from cache to author.

### CODE REVIEW

**Comment by edegraff** [comment]
Makes no fucking sense.  But hey, it works!

**Comment by afontaine** [comment]
Instructions unclear: Dick caught in Bible.

Also, if you want to jump on over to the StoryDb and change the Edit Me! story to say black square instead of white blank space, that would be suuuuper cool. If not, I'll change it once this is merge in.

**Comment by Jtfinlay** [comment]
IT MAKES PERFECT FUCKING SENSE EVAN!!!

But in all seriousness, I just dug through the current set up and figured it was some issue when the UUID was being changed for the bitmap. I figured that it probably wasn't being properly saved after the UUID change. How do you we fix bugs like this? IGNORE THE PROBLEM AND SET IT TO NULL!!! YAY

**Comment by Jtfinlay** [comment]
@afontaine : Want me to get a fun 'tutorial' icon to use for those two things?

**Comment by afontaine** [comment]
Uh... Uh... Uh.. no, because there's no god damn decent way to reach the resources from the DB set up. :frowning:

**Comment by Jtfinlay** [comment]
okay :( I have one ready if you change your mind

**Comment by afontaine** [comment]
If you can hack it to make it work, go for it. I just couldn't figure out a decent way to make it work.

**Comment by Jtfinlay** [comment]
I can hack it. Is it possible to remove the 'black' icon so that it forces the placeholder? If you can do that it would be easy

**Comment by afontaine** [comment]
It should be possible...

**Comment by Jtfinlay** [comment]
just hold on. I might have an easier way. I'll let you know if I need that..

**Comment by afontaine** [comment]
Okay, it looks like making the thumbnail null might be way too much work for 2 in the morning. Can you just look for the two UUIDs in the view and set it to your awesome image?

**Comment by Jtfinlay** [comment]
I almost have it working.. just a sec

**Comment by Jtfinlay** [comment]
I nearly have it working. It still defaults to the black icon though.. Once you actually click it, it updates. Oh well. This doesn't matter I guess. At least we have the other shit working.

**Comment by Jtfinlay** [comment]
Are we all done now?

**Comment by afontaine** [comment]
Damn... alright. Uh.. I think we're done code now.

**Pull request merged**
