### PR TITLE
Images & Fixes

### PR DESCRIPTION
**Pull request by Jtfinlay**
Bow before Thoraxis!!
- Removed placeholders from filmstrips, should load any set images (I wouldn't change any server stories until Jesse's stuff is pulled in though, just in case things don't save right).
- Thumbnails should load the right image everywhere
- Made StoryFragment View async, so that we stop only loading a few words when server is slowwwww..

Enjoy

NOTE --- I noticed that if you DL a story, change the bitmap, and reupload, the cached bitmap does not update. Have to kill cache before bitmap changes. Do we care?

### CODE REVIEW

**Comment by afontaine** [comment]
@jviau and I say fucket. I'll test in a bit.

**Comment by Jtfinlay** [comment]
Merged & fixed minor bug. Please test and merge

**Comment by Jtfinlay** [comment]
New fix: The image button in CommentView disappears if there is no image.

**Comment by edegraff** [comment]
Seems to work well, approved!

**Comment by afontaine** [comment]
Looks good to me, I'll take a look at that issue now.

**Pull request merged**
