### PR TITLE
Thumbnail and WebStorage changes/fixes

### PR DESCRIPTION
**Pull request by jviau**
Story thumbnail has been changed to be a Base64 string internally. Call Story.decodeThumbnail() to get it as a Bitmap. This caches it internally, so subsequent calls return the same thumbnail. Setting the thumbnail will cause it to be re-generated on the next decode call. The cached thumbnail and its dirty bool are "transient", they will not be serialized (as in json).

I found that ElasticSearch defaults to returning only 10 items in a search. So I implemented paging on all the queries in WebStorage() (sorry Evan, have fun hooking it up). Each query call takes in a "from" and a "size". I suggest starting with from=0 and size=10, then if you want more do from=10, size=10. Keep doing that as needed until the amount returned is < size.

This will allow us to implement proper paging in the view. Load the first 10 Stories or comments, then when the user scrolls to the bottom load the next 10 and so on.

The thumbnail change combined with paging should hopefully fix our out of memory issue. If not I will look into further changes.

### CODE REVIEW

**Comment by edegraff** [comment]
Thumbnails seems to work, hopefully that will help the memory issue.  I don't know if the paging will since we only had 3 stories stored anyway.

Approved for now, will try using the new server calls with my stuff.

**Comment by jviau** [comment]
Oh yeah I also changed one of the story constructors or public (from protected). I needed to be able to instantiate them I'm my tests. I'm not sure why they were protected in the first place.

**Comment by afontaine** [comment]
Ha that would be Jesse's doing. I'm not sure why they're protected either.
A half-assed factory pattern, perhaps?

**Comment by Jtfinlay** [comment]
I tried pulling it in with the code I was working on previously.
For StoryManager, I used: List<Story> onlineStories = m_webStorage.getStories(0, 3); temporarily.
I received [this error](http://ualberta.ca/~jtfinlay/src/log.txt).

I pushed the [branch](https://github.com/Jtfinlay/adventure.datetime/tree/server_fix) to my local repo. Thoughts? Was this my doing or something else?

This was while trying to load the stories from the Online tab of BrowseView. I reinstalled and cleaned the project, still getting error.

**Comment by jesseDtucker** [comment]
The only reason I marked them as protected was because the view was at one point directly instantiating story objects. It wasn't supposed to do that. I marked them as protected to enforce that behavior at compile time.

**Comment by jviau** [comment]
Okay that error looks like something is not thread-safe. The error itself appears to be from GSON, so I updated it to 2.2.4, which is hopefully thread-safe (the interwebs claims it is). I also made JEST use a thread safe default HTTP client. Hopefully that works as well!

**Comment by edegraff** [comment]
James approves ;)

**Pull request merged**
