### PR TITLE
More view implementation

### PR DESCRIPTION
**Pull request by Jtfinlay**
Hey guys I did more view stuff.
- Filmstrip implementation
- AuthorList implementation

Figured I'd push so that we can start getting deeper into MVC interactions.

### CODE REVIEW

**Comment by afontaine** [comment]
Action Bar back button does't work. Fix that, and it's all good.

**Comment by Jtfinlay** [comment]
Now try

**Comment by afontaine** [comment]
Looks good to me

:shipit:

**Comment by jviau** [comment]
looks good!

**Pull request merged**
